"""job board

Revision ID: a86f4d7be5e3
Revises: e10e80392138
Create Date: 2023-02-20 05:29:24.223363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86f4d7be5e3'
down_revision = 'e10e80392138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('options', sa.JSON()),
    sa.Column('super_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['super_user_id'], ['super_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_artpiece_association',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('artpiece_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artpiece_id'], ['artpieces.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('job_id', 'artpiece_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_artpiece_association')
    op.drop_table('jobs')
    # ### end Alembic commands ###
