"""add locations

Revision ID: e9475d315bf6
Revises: a86f4d7be5e3
Create Date: 2023-04-08 19:37:15.632497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9475d315bf6'
down_revision = 'a86f4d7be5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lab_object_location_association',
    sa.Column('lab_object_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lab_object_id'], ['lab_objects.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('lab_object_id', 'location_id')
    )
    op.create_table('plasmid_location_association',
    sa.Column('plasmid_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['plasmid_id'], ['plasmids.id'], ),
    sa.PrimaryKeyConstraint('plasmid_id', 'location_id')
    )
    op.create_table('strain_location_association',
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strains.id'], ),
    sa.PrimaryKeyConstraint('strain_id', 'location_id')
    )
    op.alter_column('genetic_parts', 'global_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('jobs', 'file_name',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('plasmids', 'global_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('strains', 'global_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.add_column('super_users', sa.Column('home_base_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'super_users', 'locations', ['home_base_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'super_users', type_='foreignkey')
    op.drop_column('super_users', 'home_base_id')
    op.alter_column('strains', 'global_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('plasmids', 'global_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('jobs', 'file_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('genetic_parts', 'global_id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_table('strain_location_association')
    op.drop_table('plasmid_location_association')
    op.drop_table('lab_object_location_association')
    op.drop_table('locations')
    # ### end Alembic commands ###
